server:
  port: 8090

spring:
  cloud:
    gateway:
#      discovery: 
#        locator:
#          enabled: true #if you want automated routing then you need to enable this one
#          lower-case-service-id: true
        routes[0]:
          id: book-details
          uri: lb://book-details-service
#          predicates[0]: Path=/book-details/**
          predicates[0]: "Path=/bd/**"
          predicates[1]: Method=GET
          filters[0]: RemoveRequestHeader=Cookie
          filters[1]: "RewritePath=/bd/**, /book-details/**" # changed predicate to support rewrite path filter

management:
  endpoints:
    web:
      exposure:
        include: "*"
