server:
  port: 0 #spring will assign a random port
  servlet:
    context-path: /user-details

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql://localhost:3306/userdb?useSSL=false
    username: root
    password: password
    max-active: 50
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

logging:
  level:
    org:
      hibernate:
        sql: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
            

gateway:
  ipAddress: 127.0.0.1

management:
  endpoints:
    web:
      exposure:
        include: "*"